### ISSUE TITLE
[Feature] User Authentication

### ISSUE THREAD

**Issue by hyeneung** [9oormthon-univ/2024_DANPOONG_TEAM_50_BE#1]
## Work Details
- User signup
- User login (email/password)
- Kakao login integration
- JWT for authentication and authorization
- Storing refresh tokens in Redis

## Task List
- [ ] Implement user signup API
- [ ] Implement user login API (email/password)
- [ ] Implement Kakao login API
- [ ] Create and validate JWT logic
- [ ] Generate refresh tokens and store them in Redis
- [ ] Documentation: Create API documentation and usage instructions
