### ISSUE TITLE
[Feature] Store Domain API

### ISSUE THREAD

**Issue by himodu** [9oormthon-univ/2024_DANPOONG_TEAM_50_BE#10]
## Work Details
- Implement StoreList, StoreDetail, and StoreResponse DTOs
- Implement MenuList and Menu DTOs
- Implement Store Controller, Service, and Repository
- Implement Store search based on current location and keywords
- Implement Get API for retrieving detailed Store information
- Implement Get API for retrieving Store menu
- Implement Patch API to update Store likes
## Task List
- [x] Implement StoreList, StoreDetail, and StoreResponse DTOs
- [x] Implement MenuList and Menu DTOs
- [x] Implement Store Controller, Service, and Repository
- [x] Implement Get API for searching Stores based on current location and keywords
- [x] Implement Get API for retrieving detailed Store information
- [x] Implement Get API for retrieving Store menu
- [x] Implement Patch API to update Store likes
