### ISSUE TITLE
[Feature] BookMark Domain API

### ISSUE THREAD

**Issue by himodu** [9oormthon-univ/2024_DANPOONG_TEAM_50_BE#37]
## Work Details
- Implement BookMark Entity, Repository, Controller, Service
- Implement Patch API to add Store as BookMark
- Implement Get API to show BookMarked Stores

## Task List
- [x] Implement BookMark Entity, Repository, Controller, Service
- [x] Implement Patch API to add Store as BookMark
- [x] Implement Get API to show BookMarked Stores
