### ISSUE TITLE
[Feature] Donation Statics Domain API

### ISSUE THREAD

**Issue by himodu** [9oormthon-univ/2024_DANPOONG_TEAM_50_BE#38]
## Work Details
- Implement Child Address, Store Address Entity, repository
- Implement Statics Controller, Service
- Implement Get API to show 지역별 아동 분포
- Implement Get API to show 지역별 후원금액 사용률
- Implement Get API to show 지역별 급식카드 가맹점 분포 
- Add Location when Child's SignUP

## Task List
- [x] Implement Child Address, Store Address Entity, repository
- [x] Implement Statics Controller, Service
- [x] Implement Get API to show 지역별 아동 분포
- [x] Implement Get API to show 지역별 후원금액 사용률
- [x] Implement Get API to show 지역별 급식카드 가맹점 분포 
- [x] Add Location when Child's SignUP
