### ISSUE TITLE
[Feature] Store Domain Seed

### ISSUE THREAD

**Issue by himodu** [9oormthon-univ/2024_DANPOONG_TEAM_50_BE#9]
## Work Details
- Implement connection to 경기도 급식카드 가맹점 Open API
- Implement AddressNew, AddressOld, Like, and Menu entities
- refatoring Store entities
- Implement AddressNew, AddressOld, Like, and Menu repositories
- Save Open API data as seed data in the store table
## Task List
- [x] Implement connection to 경기도 급식카드 가맹점 Open API
- [x] Implement AddressNew, AddressOld, Like, and Menu entities
- [x] refatoring Store entities
- [x] Implement AddressNew, AddressOld, Like, and Menu repositories
- [x] Implement Saving Open API data as seed data in the store table
